GamingStoreTekrar/Areas/admin_panel/Models/AllGenresModel.cs
namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class AllGenresModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/AllTagsModel.cs
namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class AllTagsModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/AllUsersModel.cs
namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class AllUsersModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public byte Age { get; set; }
        public string FullName { get; set; }
        public string ProfilePhoto { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/ChangeRoleModel.cs
using Microsoft.AspNetCore.Identity;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class ChangeRoleModel
    {
        public string Id { get; set; }
        public string? PhotoPath { get; set; }
        public string? UserName { get; set; }
        public string? Email { get; set; }
        public List<string> UserRoles { get; set; }
        public List<IdentityRole> Roles { get; set; }
        public string SelectedRoleId { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/CreateGameModel.cs
using GamingStoreTekrar.Entities;
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class CreateGameModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string ShortDesc { get; set; }
        [Required]
        public IFormFile GameImage { get; set; }
        [Required]
        public double Price { get; set; }
        public string[] Genres { get; set; }
        public string[] Tags { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/CreateGenreModel.cs
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class CreateGenreModel
    {
        [Required]
        public string Name { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/CreateTagModel.cs
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class CreateTagModel
    {
        [Required]
        public string Name { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/EditUserModel.cs
using GamingStoreTekrar.CustomValidations;
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class EditUserModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public byte Age { get; set; }
        public string PhotoPath { get; set; }
        public IFormFile? ProfilePhoto { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/EmailModel.cs
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class EmailModel
    {
        [EmailAddress]
        public string Recepient { get; set; }
        [Required]
        [MaxLength(80,ErrorMessage ="Too long for subject name")]
        public string Subject { get; set; }
        [Required]
        public string Message { get; set; }

    }
}

GamingStoreTekrar/Areas/admin_panel/Models/ErrorModel.cs
namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class ErrorModel
    {
        public string ErrorMessage { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class LoginModel
    {
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/Models/SendBatchEmailModel.cs
using GamingStoreProject.CustomValidations;
using System.ComponentModel.DataAnnotations;

namespace GamingStoreTekrar.Areas.admin_panel.Models
{
    public class SendBatchEmailModel 
    {
        [EmailListValidator]
        public List<string> Emails { get; set; }
        [Required]
        [MaxLength(80, ErrorMessage = "Too long for subject name")]
        public string Subject { get; set; }
        [Required]
        public string Message { get; set; }
    }
}

GamingStoreTekrar/Areas/admin_panel/ViewModels/GenresIndexVm.cs
using GamingStoreTekrar.Areas.admin_panel.Models;

namespace GamingStoreTekrar.Areas.admin_panel.ViewModels
{
    public class GenresIndexVm
    {
        public List<AllGenresModel> Genres { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPage { get; set; }
        public int PageSize { get; set; }
        public List<int> PageSizes { get; set; } = new() { 5, 15, 25 };
    }
}

GamingStoreTekrar/Areas/admin_panel/Controllers/AuthController.cs
using CloudinaryDotNet.Actions;
using GamingStoreTekrar.Areas.admin_panel.Models;
using GamingStoreTekrar.Data;
using GamingStoreTekrar.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GamingStoreTekrar.Areas.admin_panel.Controllers
{
    [Area("admin_panel")]
    public class AuthController : Controller
    {
        public AuthController(AppDbContext appDbContext, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _appDbContext = appDbContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        private readonly AppDbContext _appDbContext;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public IActionResult Login()
        {
            return View();
        }

        [Authorize(Roles = nameof(Role.Admin), AuthenticationSchemes = "AdminAuth")]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(scheme: "AdminAuth");

            return RedirectToAction("Login","Auth");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var usr = await _userManager.FindByEmailAsync(model.Email);

            if(usr == null)
            {
                ModelState.AddModelError("authError", "There isn't such admin");
                return View(model);
            }

            var res = await _signInManager.CheckPasswordSignInAsync(usr,model.Password,false);
            
            if (!res.Succeeded)
            {
                ModelState.AddModelError("authError", "Password or email is wrong!");
                return View(model);
            }
            
            var claimsPrinc = await _signInManager.CreateUserPrincipalAsync(usr);

            await HttpContext.SignInAsync("AdminAuth",claimsPrinc);



            return RedirectToAction("Index", "Home");
        }
    }
}

GamingStoreTekrar/Areas/admin_panel/Controllers/GamesController.cs
using GamingStoreTekrar.Abstractions;
using GamingStoreTekrar.Areas.admin_panel.Models;
using GamingStoreTekrar.Data;
using GamingStoreTekrar.Entities;
using GamingStoreTekrar.Enums;
using GamingStoreTekrar.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GamingStoreTekrar.Areas.admin_panel.Controllers
{
    [Area("admin_panel")]
    [Authorize(Roles = nameof(RoleTypes.Admin), AuthenticationSchemes = "AdminAuth")]
    public class GamesController : Controller
    {
        public GamesController(IStorageService storageService, AppDbContext context)
        {
            _storageService = storageService;
            _context = context;
        }

        private readonly IStorageService _storageService;
        private readonly AppDbContext _context;


        public async Task<IActionResult> Create()
        {
            var genres = await _context.Genres.ToListAsync();
            var tags = await _context.GameTags.ToListAsync();

            ViewData["genres"] = genres;
            ViewData["tags"] = tags;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var dto = await _storageService.UploadFileAsync("game-photos", model.GameImage);

            if (_storageService is LocalStorageService)
            {
                dto.FullPath = $"uploads/{dto.FullPath}";
            }


            var selecetedGenres = await _context.Genres
                .Where(g => model.Genres.Contains(g.Id.ToString()))
                .ToListAsync();

            var selecetedTags = await _context.GameTags
                .Where(t => model.Tags.Contains(t.Id.ToString()))
                .ToListAsync();

            var game = new Game()
            {
                Id = Guid.NewGuid(),
                Name = model.Name,
                ShortDesc = model.ShortDesc,
                Description = model.Description,
                ClickCount = 0,
                IsDeleted = false,
                Price = model.Price,
                PhotoPath = dto.FullPath,
                CreatedDate = DateTime.UtcNow,
                Genres = selecetedGenres,
                GameTags = selecetedTags
            };

            await _context.Games.AddAsync(game);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

GamingStoreTekrar/Areas/admin_panel/Controllers/GenresController.cs
using GamingStoreTekrar.Areas.admin_panel.Models;
using GamingStoreTekrar.Areas.admin_panel.ViewModels;
using GamingStoreTekrar.Data;
using GamingStoreTekrar.Entities;
using GamingStoreTekrar.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GamingStoreTekrar.Areas.admin_panel.Controllers
{
    [Area("admin_panel")]
    [Authorize(Roles = nameof(RoleTypes.Admin), AuthenticationSchemes = "AdminAuth")]
    public class GenresController : Controller
    {
        public GenresController(AppDbContext context)
        {
            _context = context;
        }

        private readonly AppDbContext _context;

        public async Task<IActionResult> AllGenres(int page = 1, int size = 5)
        {
            var genres = await _context.Genres
                .Skip((page - 1) * size)
                .Take(size)
                .Where(g => !g.IsDeleted)
                .Select(g => new AllGenresModel()
            {
                Id = g.Id.ToString(),
                Name = g.Name,
                CreatedDate = g.CreatedDate
            }).ToListAsync();

            var totalGenres = _context.Genres.Count();

            var vm = new GenresIndexVm()
            {
                CurrentPage = page,
                PageSize = size,
                TotalPage = (int)Math.Ceiling(totalGenres / (double)size),
                Genres = genres
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View();
        }


        public async Task<IActionResult> Delete(string genreId)
        {
            if(string.IsNullOrWhiteSpace(genreId) || !Guid.TryParse(genreId,out Guid id))
            {

                var errorModel = new ErrorModel()
                {
                    ErrorMessage = "The given id isn't correct format" 
                };
                return View("Error",errorModel);
            }

            var genre = await _context.Genres.FindAsync(id);

            if(genre == null)
            {
                var errorModel = new ErrorModel()
                {
                    ErrorMessage = "There isn't such genre"
                };
                return View("Error",errorModel);
            }

            //_context.Genres.Remove(genre);
            //await _context.SaveChangesAsync();

            genre.IsDeleted = true;
            await _context.SaveChangesAsync();

            return View("Index","Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGenreModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var genre = new Genre()
            {
                Id = Guid.NewGuid(),
                Name = model.Name,
                CreatedDate = DateTime.UtcNow,
            };

            await _context.Genres.AddAsync(genre);
            await _context.SaveChangesAsync();

            return RedirectToAction("AllGenres");
        }

    }
}

GamingStoreTekrar/Areas/admin_panel/Controllers/HomeController.cs
using GamingStoreTekrar.Abstractions;
using GamingStoreTekrar.Areas.admin_panel.Models;
using GamingStoreTekrar.Data;
using GamingStoreTekrar.Dtos;
using GamingStoreTekrar.Enums;
using GamingStoreTekrar.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MimeKit;

namespace GamingStoreTekrar.Areas.admin_panel.Controllers
{
    [Area("admin_panel")]
    [Authorize(Roles = nameof(RoleTypes.Admin), AuthenticationSchemes = "AdminAuth")]
    public class HomeController : Controller
    {
        public HomeController(IEmailService emailService, AppDbContext context)
        {
            _emailService = emailService;
            _context = context;
        }

        private readonly IEmailService _emailService;
        private readonly AppDbContext _context;

        public IActionResult Index()
        {
            ViewBag.totalUsers = _context.Users.Count();
            ViewBag.totalGames = _context.Games.Where(g => !g.IsDeleted).Count();
            ViewBag.totalViews = _context.Games.Where(g => !g.IsDeleted).Sum(g => g.ClickCount);
            ViewBag.totalGenres = _context.Genres.Where(gnr => !gnr.IsDeleted).Count();
            ViewBag.totalTags = _context.GameTags.Where(t => !t.IsDeleted).Count();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendMail(EmailModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index",model);
            }

            var dto = new MailDto()
            {
                Addresses = new List<MailboxAddress>() 
                {
                    new MailboxAddress("receiver",model.Recepient)
                },
                Subject = model.Subject,
                Content = model.Message
            };

            await _emailService.SendAsync(dto);

            return RedirectToAction("Index");
        }
    }
}

GamingStoreTekrar/Areas/admin_panel/Controllers/TagsController.cs
using GamingStoreTekrar.Areas.admin_panel.Models;
using GamingStoreTekrar.Areas.admin_panel.ViewModels;
using GamingStoreTekrar.Data;
using GamingStoreTekrar.Entities;
using GamingStoreTekrar.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GamingStoreTekrar.Areas.admin_panel.Controllers
{
    [Area("admin_panel")]
    [Authorize(Roles = nameof(RoleTypes.Admin), AuthenticationSchemes = "AdminAuth")]
    public class TagsController : Controller
    {
        public TagsController(AppDbContext context)
        {
            _context = context;
        }

        private readonly AppDbContext _context;

        public async Task<IActionResult> AllTags(int page = 1, int size = 5)
        {
            var tags = await _context.GameTags
                .Skip((page - 1) * size)
                .Take(size)
                .Select(t => new AllTagsModel()
                {
                    Id = t.Id.ToString(),
                    Name = t.Name,
                    CreatedDate = t.CreatedDate
                }).ToListAsync();

            var totalTags = _context.GameTags.Count();

            var vm = new TagsIndexVm()
            {
                CurrentPage = page,
                PageSize = size,
                TotalPage = (int)Math.Ceiling(totalTags / (double)size),
                Tags = tags
            };

            return View(vm);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTagModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var tag = new GameTag()
            {
                Id = Guid.NewGuid(),
                Name = model.Name,
                CreatedDate = DateTime.UtcNow,
            };

            await _context.GameTags.AddAsync(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction("AllTags");
        }
    }
}

GamingStoreTekrar/Areas/admin_panel/Views/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GameStore Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/7.4.47/css/materialdesignicons.min.css" integrity="sha512-/k658G6UsCvbkGRB3vPXpsPHgWeduJwiWGPCGS14IQw3xpr63AEMdA8nMYG2gmYkXitQxDTn6iiK/2fD4T87qA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/admin/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/admin/css/style.css">
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex justify-content-center">
                <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                    <a class="navbar-brand brand-logo" href="index.html"><img src="~/admin/images/turboaz-logo.png" alt="logo" /></a>
                    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/admin/images/turboaz-logo.png" alt="logo" /></a>
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-sort-variant"></span>
                    </button>
                </div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
                            <span class="nav-profile-name">Admin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                            <a asp-action="LogOut" asp-controller="Auth" class="dropdown-item">
                                <i class="mdi mdi-logout text-primary"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link active" asp-action="Index" asp-controller="Home">
                            <i class="mdi mdi-home menu-icon"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-users" aria-expanded="false" aria-controls="ui-users">
                            <i class="mdi mdi-account menu-icon"></i>
                            <span class="menu-title">Users</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-users">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" asp-action="AllUsers" asp-controller="Users">All Users</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="Create" asp-controller="Users">Create User</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="SendBatchEmail" asp-controller="Users">Send Batch Email</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-games" aria-expanded="false" aria-controls="ui-games">
                            <i class="mdi mdi-controller menu-icon"></i>
                            <span class="menu-title">Games</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-games">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" asp-action="AllGames" asp-controller="Games">All Games</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="AllGames" asp-controller="Games">Deleted Games</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="Create" asp-controller="Games">Create Game</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-blogs" aria-expanded="false" aria-controls="ui-blogs">
                            <i class="mdi mdi-newspaper menu-icon"></i>
                            <span class="menu-title">Blogs</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-blogs">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" href="#">All Blogs</a></li>
                                <li class="nav-item"> <a class="nav-link" href="#">Deleted Blogs</a></li>
                                <li class="nav-item"> <a class="nav-link" href="#">Create Blog</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-genres" aria-expanded="false" aria-controls="ui-genres">
                            <i class="mdi mdi-drama-masks menu-icon"></i>
                            <span class="menu-title">Genres</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-genres">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" asp-action="AllGenres" asp-controller="Genres">All Genres</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="Create" asp-controller="Genres">Create Genre</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-tags" aria-expanded="false" aria-controls="ui-tags">
                            <i class="mdi mdi-tag menu-icon"></i>
                            <span class="menu-title">Game Tags</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-tags">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" asp-action="AllTags" asp-controller="Tags">All Tags</a></li>
                                <li class="nav-item"> <a class="nav-link" asp-action="Create" asp-controller="Tags">Create Tag</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best <a href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard  </a> templates</span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/admin/vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/admin/vendors/chart.js/Chart.min.js"></script>
    <script src="~/admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/admin/js/off-canvas.js"></script>
    <script src="~/admin/js/hoverable-collapse.js"></script>
    <script src="~/admin/js/template.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/admin/js/dashboard.js"></script>
    <script src="~/admin/js/data-table.js"></script>
    <script src="~/admin/js/jquery.dataTables.js"></script>
    <script src="~/admin/js/dataTables.bootstrap4.js"></script>
    <!-- End custom js for this page-->

    <script src="~/admin/js/jquery.cookie.js" type="text/javascript"></script>
    @RenderSection("SpecialJs",false)
</body>

</html>